<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="webdriver" duration-ms="59812" started-at="2014-11-13T10:06:35Z" finished-at="2014-11-13T10:07:35Z">
    <groups>
    </groups>
    <test name="Practice3OnTestng" duration-ms="59812" started-at="2014-11-13T10:06:35Z" finished-at="2014-11-13T10:07:35Z">
      <class name="Test.TestCase.Practicethree.Practice3OnTestng">
        <test-method status="PASS" signature="init(java.lang.String, java.lang.String)[pri:0, instance:Test.TestCase.Practicethree.Practice3OnTestng@145e044]" name="init" is-config="true" duration-ms="24027" started-at="2014-11-13T18:06:35Z" finished-at="2014-11-13T18:06:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[/tools/test.properties]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/tools/Locator.properties]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="loginTest()[pri:0, instance:Test.TestCase.Practicethree.Practice3OnTestng@145e044]" name="loginTest" duration-ms="7778" started-at="2014-11-13T18:06:59Z" finished-at="2014-11-13T18:07:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="contactsTest()[pri:0, instance:Test.TestCase.Practicethree.Practice3OnTestng@145e044]" name="contactsTest" duration-ms="25610" started-at="2014-11-13T18:07:07Z" depends-on-methods="Test.TestCase.Practicethree.Practice3OnTestng.loginTest" finished-at="2014-11-13T18:07:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [100] but found [466]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [100] but found [466]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at Test.TestCase.Practicethree.Practice3OnTestng.contactsTest(Practice3OnTestng.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactsTest -->
        <test-method status="PASS" signature="release()[pri:0, instance:Test.TestCase.Practicethree.Practice3OnTestng@145e044]" name="release" is-config="true" duration-ms="2383" started-at="2014-11-13T18:07:33Z" finished-at="2014-11-13T18:07:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- release -->
      </class> <!-- Test.TestCase.Practicethree.Practice3OnTestng -->
    </test> <!-- Practice3OnTestng -->
  </suite> <!-- webdriver -->
</testng-results>
